### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by JohnWeak1** [TominoCZ/FancyBlockParticles#101]
## Steps to reproduce issue:
while forge is loading mods

## MC Version:
MC 1.12

## FBP Version:
FBP 2.4.0 1.12.X

## Forge Version (e.g. 2604):
forge 1.12-14.21.0.2335
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore+v1.8.10+mc1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  ASMPlugin (Squake-Mod-1.12.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  BetterFoliageLoader (BetterFoliage-1.12.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/13/18 7:14 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fancy Block Particles (fbp)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:583)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:233)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.registries.IForgeRegistryEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 289413728 bytes (276 MB) / 570425344 bytes (544 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.0.2335 Optifine OptiFine_1.12_HD_U_C3 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2335.jar) 
	UC	forge{14.21.0.2335} [Minecraft Forge] (forge-1.12-14.21.0.2335.jar) 
	UC	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UC	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UC	betterfoliage{2.1.9} [Better Foliage] (BetterFoliage-1.12.jar) 
	UC	chunkanimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.12-1.2.jar) 
	UC	creativecore{1.7.4} [CreativeCore] (CreativeCore+v1.8.10+mc1.12.jar) 
	UE	dsurround{3.4.7.2} [Dynamic Surroundings] (DynamicSurroundings-1.12.2-3.4.7.2.jar) 
	UC	presets{3.4.7.2} [Presets!] (DynamicSurroundings-1.12.2-3.4.7.2.jar) 
	UE	fbp{2.3.8} [Fancy Block Particles] (FancyBlockParticles-1.12.x-2.3.8.jar) 
	UC	hud{1.3.9} [Better HUD] (hud-1.3.9-1.12.jar) 
	UC	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UC	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UC	squeedometer{1.0.4} [Squeedometer] (Squeedometer-mc1.12.x-1.0.4.jar) 
	UC	squake{1.0.4} [Squake] (Squake-Mod-1.12.jar) 
	UC	stellarapi{1.12.2-0.4.2.9} [Stellar API] (Stellar+API-1.12.2-0.4.2.9.jar) 
	UC	stellarsky{1.12.2-0.5.2.8} [Stellar Sky] (Stellar+Sky-1.12.2-0.5.2.8.jar) 
	UC	bspkrscore{at_0.9} [bspkrsCore] (Treecapitator-1.12-at_0.9.jar) 
	UC	treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.12-at_0.9.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore+v1.8.10+mc1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
ASMPlugin (Squake-Mod-1.12.jar)
  squeek.quakemovement.ASMPlugin
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-1.12.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12_HD_U_C3
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.82
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by TominoCZ** [comment]
I can't tell what happened from the crash log, but this doesn't look like it's my mod. Try Fancy Block Particles without the other mods.

**Comment by TominoCZ** [comment]
Hmm.. It could be the version of Forge that you're using. Make sure you're using the latest recommended version (version 2768).

**Comment by illuminator3** [comment]
This happens because you are using a corrupted forge version. Apparently a class is not present in your forge installation.
